image: ubuntu

before_script:
      - apt update
  
deployment:
    tags:
        - AWS
    script:
        - 'command -v ssh-agent > /dev/null || apt-get update -y && apt-get install openssh-client -y'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r'| ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh ubuntu@3.122.246.39 -o "StrictHostKeyChecking=no" 'cd app; git pull; sudo service apache2 restart; exit'
        - ssh ubuntu@18.195.173.8 -o "StrictHostKeyChecking=no" 'cd app; git pull; sudo service apache2 restart;'